# Generated by Django 4.1.3 on 2022-11-26 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_transaction_date_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 1, 24, 34, 340520)),
        ),
    ]
